### ISSUE TITLE
Update ExaMiniMD for Kokkos v3.0 promotion

### ISSUE THREAD

**Issue by alanphumphrey** [ECP-copa/ExaMiniMD#27]
I'm a research computer scientist at the University of Utah, doing contract work for Sandia ABQ. Christian Trott has asked that I update the Kokkos miniApps repository for the Kokkos v3.0 promotion. As I'm not a direct contributor to ExaMiniMD, I cannot self-assign this issue.

I've updated ExaMiniMD and will submit a pull request.

**Comment by stanmoore1** [comment]
Sounds good, thanks @alanphumphrey

**Comment by stanmoore1** [comment]
Fixed by #28. Closing #27.
