### ISSUE TITLE
Typo for enable MPI compile definition in src/CMakeLists.txt

### ISSUE THREAD

**Issue by akhilred36** [ECP-copa/ExaMiniMD#35]
compile definition should be 
`target_compile_definitions(ExaMiniMD PRIVATE EXAMINIMD_ENABLE_MPI)` , but currently is 
`target_compile_definitions(ExaMiniMD PRIVATE EXAMIND_ENABLE_MPI) `

**Comment by stanmoore1** [comment]
@akhilred36 thanks for reporting.
